export const restaurants = [
  {
    name: "Kod Kapetana",
    id: 0,
    location: "Belgrade, Serbia",
    rating: 4.8,
    ETA: 30,
    Tags: ["Serbian", "Mediterranean"],
    photo: "/static/restaurants/kod_kapetana.jpg",
  },
  {
    name: "Inari Wok Bar",
    id: 1,
    location: "Sarajevo, Bosnia and Herzegovina",
    rating: 4.3,
    ETA: 20,
    Tags: ["Bosnian", "Asian Fusion"],
    photo: "/static/restaurants/inari_wok_bar.jpg",
  },
  {
    name: "Šestica",
    id: 2,
    location: "Ljubljana, Slovenia",
    rating: 4.6,
    ETA: 25,
    Tags: ["Slovenian", "Mediterranean"],
    photo: "/static/restaurants/sestica.jpg",
  },
  {
    name: "Orient Express",
    id: 3,
    location: "Skopje, North Macedonia",
    rating: 4.5,
    ETA: 35,
    Tags: ["Macedonian", "Mediterranean"],
    photo: "/static/restaurants/orient_express.jpg",
  },
  {
    name: "Dubravkin Put",
    id: 4,
    location: "Zagreb, Croatia",
    rating: 4.2,
    ETA: 20,
    Tags: ["Croatian", "Mediterranean"],
    photo: "/static/restaurants/dubravkin_put.jpg",
  },
  {
    name: "Konoba Akustik",
    id: 5,
    location: "Herceg Novi, Montenegro",
    rating: 4.1,
    ETA: 25,
    Tags: ["Montenegrin", "Mediterranean"],
    photo: "/static/restaurants/konoba_akustik.jpg",
  },
  {
    name: "Kod Joze",
    id: 6,
    location: "Belgrade, Serbia",
    rating: 4.4,
    ETA: 30,
    Tags: ["Serbian", "Mediterranean"],
    photo: "/static/restaurants/kod_joze.jpg",
  },
  {
    name: "Kod Keme",
    id: 7,
    location: "Sarajevo, Bosnia and Herzegovina",
    rating: 4.0,
    ETA: 35,
    Tags: ["Bosnian", "Mediterranean"],
    photo: "/static/restaurants/kod_keme.jpg",
  },
  {
    name: "Vodenica Mulino",
    id: 8,
    location: "Ohrid, North Macedonia",
    rating: 4.7,
    ETA: 20,
    Tags: ["Macedonian", "Mediterranean"],
    photo: "/static/restaurants/vodenica_mulino.jpg",
  },
  {
    name: "Gostilna As",
    id: 9,
    location: "Ljubljana, Slovenia",
    rating: 4.9,
    ETA: 15,
    Tags: ["Slovenian", "Mediterranean"],
    photo: "/static/restaurants/gostilna_as.jpg",
  },
];
